---
driver:
  name: docker
  privileged: true
  use_sudo: false

platforms:
  - name: centos-69-chef-12
    driver_config:
      require_chef_omnibus: "12.7.2"
      image: centos:6.9
      privileged: true
      provision_command:
        - yum install epel-release -y
        - yum update yum ca-certificates -y
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12.7.2 && rm install.sh

provisioner:
  name: chef_solo

verifier:
  name: inspec

suites:
  - name: varnish
    run_list:
        - varnish
#    verifier:
#      inspec_tests:
#        - tests/node.rb
#        - tests/yarn.rb
