language: ruby
dist: trusty

matrix:
  include:
    - rvm: 2.4
      env: suite=varnish-centos-7
    - rvm: 2.4
      env: suite=varnish-881-centos-7
    - rvm: 2.4
      env: suite=varnish-881-with-backend-centos-7-with-nginx
    - rvm: 2.4
      env: suite=varnish5-881-with-backend-centos-7-with-nginx
    - rvm: 2.4
      env: suite=varnish-881-with-backend-centos-7
    - rvm: 2.4
      env: suite=varnish5-881-with-backend-centos-7

sudo: required
services: docker

before_script:
  - make install
  - make bundle
  - make style

script: bundle exec kitchen test "$suite"
