#!/bin/bash
FILE="/etc/varnish/default.vcl"

# Hostname and management port
# (defined in /etc/default/varnish or on startup)
HOSTPORT="127.0.0.1:6082"
NOW=`date +%s`
SECRET='/etc/varnish/secret'

NAME=$1
if [ -z "$NAME" ]
then
NAME="reload$NOW"
fi

error()
{
    echo 1>&2 "Failed to reload $FILE."
    exit 1
}

varnishadm -T $HOSTPORT -S $SECRET vcl.load $NAME $FILE || error
varnishadm -T $HOSTPORT -S $SECRET vcl.use $NAME || error
echo Current configs:
varnishadm -T $HOSTPORT -S $SECRET vcl.list
